Repository BaSP-m2022/martina-trackgenix-app, pull requests merged in 2022-07, with the labels that each got.

#58 BaSP-TG-87: log in front
  package-lock.json
  package.json
  src/Components/Employee/Home/home.module.css
  src/Components/Employee/Sign-up/index.jsx
  src/Components/Home/index.js
  src/Components/Layout/index.js
  src/Components/Log-in/index.jsx
  src/Components/Log-in/log-in.module.css
  src/helper/firebase/index.js
  src/redux/auth/actions.js
  src/redux/auth/constants.js
  src/redux/auth/thunks.js
  src/redux/employees/thunks.js
Labels: Ready for QA

#61 BaSP-TG-95: Private routes
  package-lock.json
  package.json
  src/Components/Auth/Login/index.jsx
  src/Components/Auth/Login/login.module.css
  src/Components/Auth/NotAllowed/index.jsx
  src/Components/Auth/NotAllowed/notAllowed.module.css
  src/Components/Auth/SignUp/index.jsx
  src/Components/Auth/SignUp/sign-up.module.css
  src/Components/Employee/Profile/index.jsx
  src/Components/Employee/Projects/index.jsx
  src/Components/Employee/TimeSheet/index.jsx
  src/Components/Employee/index.js
  src/Components/Home/Home.jsx
  src/Components/Home/index.js
  src/Components/Layout/index.js
  src/Components/Shared/Layout/index.js
  src/Components/Shared/Layout/layout.module.css
  src/Components/Shared/NavBar/NavBar.jsx
  src/Routes/PrivateRoute.jsx
  src/Routes/admin.jsx
  src/Routes/auth.jsx
  src/Routes/employee.jsx
  src/Routes/home.jsx
  src/Routes/index.jsx
  src/index.js
  src/redux/auth/reducer.js
  src/redux/auth/thunks.js
Labels: Ready for Deploy!

#67 Hotfix: Update Row and Table shared components
  src/Components/Shared/Field/Input.jsx
  src/Components/Shared/Row/Row.jsx
  src/Components/Shared/Row/row.module.css
  src/Components/Shared/Table/Table.jsx
Labels: Ready for Deploy!, Priority

#68 BaSP-TG-112: Admin Flow - add/edit projects
  src/Components/Admin/Home/index.js
  src/Components/Admin/Projects/Form/EmployeeForm.jsx
  src/Components/Admin/Projects/Form/ProjectForm.jsx
  src/Components/Admin/Projects/Form/projectForm.module.css
  src/Components/Admin/Projects/List/List.jsx
  src/Components/Admin/Projects/index.js
  src/Components/Employee/Home/index.js
  src/Components/Shared/Field/Input.jsx
  src/Routes/admin.jsx
  src/redux/projects/thunks.js
Labels: Ready for Deploy!

#66 BaSP-TG-116: Super admin ABM - front
  src/Components/Admin/Projects/index.js
  src/Components/Admin/SuperAdmins/index.js
  src/Components/Admin/TimeSheets/index.js
  src/Components/Admin/index.js
  src/Components/Auth/SignUp/index.jsx
  src/Components/Auth/SignUp/sign-up.module.css
  src/Components/Shared/Layout/index.js
  src/Components/Shared/NavBar/NavBar.jsx
  src/Components/Shared/index.js
  src/Components/SuperAdmin/Admins/Form/AdminForm.jsx
  src/Components/SuperAdmin/Admins/Form/adminForm.module.css
  src/Components/SuperAdmin/Admins/admins.module.css
  src/Components/SuperAdmin/Admins/index.js
  src/Components/SuperAdmin/Employees/employees.module.css
  src/Components/SuperAdmin/Employees/index.js
  src/Components/SuperAdmin/Home/home.jsx
  src/Components/SuperAdmin/Home/home.module.css
  src/Components/SuperAdmin/Projects/index.js
  src/Components/SuperAdmin/Projects/projects.module.css
  src/Routes/SuperAdmin.jsx
  src/Routes/admin.jsx
  src/Routes/auth.jsx
  src/Routes/employee.jsx
  src/Routes/home.jsx
  src/Routes/index.jsx
  src/redux/admins/actions.js
  src/redux/admins/constants.js
  src/redux/admins/reducer.js
  src/redux/admins/thunks.js
Labels: Ready for Deploy!

#70 TG-109: Profile Employee
  public/assets/images/Tgenix.png
  src/Components/Employee/Profile/index.jsx
  src/Components/Employee/Profile/profile.module.css
  src/Components/Shared/Field/input.module.css
Labels: Ready for Deploy!

#71 BaSP-Feature-TG-110: Employee time-sheet
  package-lock.json
  package.json
  src/Components/Employee/TimeSheet/Form/Form.jsx
  src/Components/Employee/TimeSheet/Form/form.module.css
  src/Components/Employee/TimeSheet/index.jsx
  src/Components/Employee/TimeSheet/timesheets.module.css
  src/Components/Shared/Field/Input.jsx
Labels: Ready for Deploy!

#74 BaSP-Hotfix-TG-126: Login error message
  src/Components/Auth/Login/index.jsx
Labels: Ready for Deploy!

#63 feature-TG-113: admin list/delete projects
  src/Components/Admin/Projects/Form/projectForm.module.css
  src/Components/Admin/Projects/List/List.jsx
  src/Components/Admin/Projects/List/list.module.css
  src/Components/Admin/Projects/index.js
  src/Components/Admin/Projects/projects.module.css
  src/redux/projects/actions.js
  src/redux/projects/constants.js
  src/redux/projects/reducer.js
  src/redux/projects/thunks.js
Labels: Ready for Deploy!

#75 BaSP-Feature-TG-128: Admins validations and css fix
  src/Components/SuperAdmin/Admins/Form/AdminForm.jsx
  src/Components/SuperAdmin/Admins/Form/adminForm.module.css
Labels: Ready for review

#77 BaSP-TG-133: add timsheet validations, fix sign-up and add styles in forms
  src/Components/Auth/Login/index.jsx
  src/Components/Auth/Login/login.module.css
  src/Components/Auth/SignUp/index.jsx
  src/Components/Auth/SignUp/sign-up.module.css
  src/Components/Employee/Projects/index.jsx
  src/Components/Employee/TimeSheet/Form/Form.jsx
  src/Components/Employee/TimeSheet/index.jsx
  src/Components/Shared/Modal/modal.module.css
  src/Routes/home.jsx
  src/redux/employees/thunks.js
  src/redux/tasks/reducer.js
Labels: Ready for Deploy!

#78 hotfix-TG-107:
  src/Components/Admin/Employees/employees.module.css
  src/Components/Employee/TimeSheet/index.jsx
  src/Components/Shared/Loader/loader.module.css
  src/redux/employees/thunks.js
Labels: Ready for Deploy!

#80 BaSP-TG-131: Fix Buttons and change button "close" => "x"
  src/Components/Admin/Projects/Form/ProjectForm.jsx
  src/Components/Admin/Projects/Form/projectForm.module.css
  src/Components/Auth/SignUp/index.jsx
  src/Components/Employee/Profile/index.jsx
  src/Components/Employee/Projects/Form/EmployeeForm.jsx
  src/Components/Employee/Projects/Form/projectForm.module.css
  src/Components/Employee/Projects/Tasks/Form/Form.jsx
  src/Components/Employee/Projects/Tasks/Form/form.module.css
  src/Components/Employee/Projects/Tasks/tasks.module.css
  src/Components/Employee/Projects/index.jsx
  src/Components/Employee/TimeSheet/Form/Form.jsx
  src/Components/Employee/TimeSheet/Form/form.module.css
  src/Components/Shared/Buttons/buttons.module.css
  src/Components/SuperAdmin/Admins/Form/AdminForm.jsx
  src/Components/SuperAdmin/Admins/Form/adminForm.module.css
  src/Components/SuperAdmin/Admins/index.js
Labels: Ready for Deploy!

#79 BaSP-TG-134: Hotfix - Correct SuperAdmin flow and details
  src/Components/Admin/Employees/index.js
  src/Components/Admin/Projects/Form/EmployeeForm.jsx
  src/Components/Admin/Projects/Form/ProjectForm.jsx
  src/Components/Admin/SuperAdmins/index.js
  src/Components/Admin/TimeSheets/index.js
  src/Components/Auth/Login/index.jsx
  src/Components/Auth/SignUp/index.jsx
  src/Components/Employee/Profile/index.jsx
  src/Components/Employee/Projects/Form/EmployeeForm.jsx
  src/Components/Employee/Projects/Form/ProjectForm.jsx
  src/Components/Employee/Projects/Tasks/Form/Form.jsx
  src/Components/Employee/Projects/index.jsx
  src/Components/Employee/TimeSheet/Form/Form.jsx
  src/Components/Employee/TimeSheet/index.jsx
  src/Components/Shared/Layout/index.js
  src/Components/Shared/Row/Row.jsx
  src/Components/Shared/Table/Table.jsx
  src/Components/SuperAdmin/Admins/index.js
  src/Components/SuperAdmin/Employees/index.js
  src/Components/SuperAdmin/Projects/index.js
Labels: Ready for Deploy!
